name: Tests

on:
  push:

jobs:
  tests:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make libconfig++-dev

      - name: Build project
        run: make

      - name: Run tests
        run: make test
